<a href="https://colab.research.google.com/github/SingeWarden/Embeddings-Checker/blob/main/Embeddings%20Checker.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#EMBEDDING STORAGE

The below cells store, generate, and scan the embeddings files.
Original script created by @BeansBeansBeans

Upload your embeddings file (should be named embeddings.pt) to /content/ and the output will be in /content/

In [ ]:
import os

!pip install fickling &> /dev/null
fileToEncode = "/content/embeddings.pt"
fileName = "embeddings.pt"

generate = True
## Create the base64 string and print it to the cell output.  
## This is where the contents of "b64" came from.  
if os.path.exists(fileToEncode) and generate:
  !unzip -p -q -j "{fileToEncode}" archive/data.pkl | fickling -
  !zip -q - "{fileToEncode}" | base64 > "/content/{fileName}.zb64"
  !sha256sum "{fileToEncode}" 
  b64 = ''
  with open(f"/content/{fileName}.zb64", "r") as fileb64:
    for line in fileb64:
      b64 += line.strip()
  print(b64)

else:
  raise Exception("File not found in /content/")

with open(f"/content/{fileName}.zb64", "w") as outFile:
  outFile.write(b64)

!cat "/content/{fileName}.zb64" | base64 -d > "/content/{fileName}.zip"
!unzip -p "/content/{fileName}.zip" > "/content/{fileName}"
!rm "/content/{fileName}.zb64"
!rm "/content/{fileName}.zip"
#This section scans the embedding that was just inflated
!unzip -p -q -j "/content/{fileName}" archive/data.pkl | fickling -
!echo "sha256sum /content/{fileName}"
!sha256sum "/content/{fileName}"


from torch._utils import _rebuild_tensor_v2
from torch import LongStorage
from collections import OrderedDict
_var0 = OrderedDict()
_var1 = _rebuild_tensor_v2(UNPICKLER.persistent_load(('storage', LongStorage, '0', 'cpu', 77)), 1, (), (), False, _var0)
from torch.nn.modules.container import ParameterDict
_var2 = OrderedDict()
from torch._utils import _rebuild_parameter
from torch import FloatStorage
_var3 = OrderedDict()
_var4 = _rebuild_tensor_v2(UNPICKLER.persistent_load(('storage', FloatStorage, '1', 'cuda:0', 73728)), 0, (96, 768), (768, 1), False, _var3)
_var5 = OrderedDict()
_var6 = _rebuild_parameter(_var4, True, _var5)
_var7 = _var2
_var7['*'] = _var6
_var8 = OrderedDict()
_var9 = set([])
_var10 = OrderedDict()
_var11 = OrderedDict()
_var12 = OrderedDict()
_var13 = OrderedDict()
_var14 = OrderedDict()
_var15 = OrderedDict()
_var16 = OrderedDict()
_var17 = ParameterDict()
_var17.__setstate__({'training': True, '_parameters': _var7, '_buffers': _var8, '_non_persistent_buffers_se

You should know that embeddings.pt (and .bin) files will execute code on your system when you import them.  This validation step is an example of how to make 100% sure the contents are not malicious.  Compare the output of the above cell to the text below to verify the contents of the embedding:

```from torch._utils import _rebuild_tensor_v2
from torch import LongStorage
from collections import OrderedDict
_var0 = OrderedDict()
_var1 = _rebuild_tensor_v2(UNPICKLER.persistent_load(('storage', LongStorage, '0', 'cpu', 77)), 1, (), (), False, _var0)
from torch.nn.modules.container import ParameterDict
_var2 = OrderedDict()
from torch._utils import _rebuild_parameter
from torch import FloatStorage
_var3 = OrderedDict()
_var4 = _rebuild_tensor_v2(UNPICKLER.persistent_load(('storage', FloatStorage, '1', 'cuda:0', 73728)), 0, (96, 768), (768, 1), False, _var3)
_var5 = OrderedDict()
_var6 = _rebuild_parameter(_var4, True, _var5)
_var7 = _var2
_var7['*'] = _var6
_var8 = OrderedDict()
_var9 = set([])
_var10 = OrderedDict()
_var11 = OrderedDict()
_var12 = OrderedDict()
_var13 = OrderedDict()
_var14 = OrderedDict()
_var15 = OrderedDict()
_var16 = OrderedDict()
_var17 = ParameterDict()
_var17.__setstate__({'training': True, '_parameters': _var7, '_buffers': _var8, '_non_persistent_buffers_set': _var9, '_backward_hooks': _var10, '_is_full_backward_hook': None, '_forward_hooks': _var11, '_forward_pre_hooks': _var12, '_state_dict_hooks': _var13, '_load_state_dict_pre_hooks': _var14, '_load_state_dict_post_hooks': _var15, '_modules': _var16, '_keys': {'*': None}})
result = {'string_to_token': {'*': _var1}, 'string_to_param': _var17}

sha256sum /content/cartoon_dicks.pt
143283ac00375ad688f686181706336cd7b0bc6dd805324939f3c5bdd19c046c  /content/cartoon_dicks.pt
```

